version: '3'

services:
  server:
    build: ./lb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./lb/src:/var/www/html
      - ./lb/ssl:/etc/nginx/ssl

  app1:
    build: ./app
    volumes:
      - ./app:/app
  app2:
    build: ./app
    volumes:
      - ./app:/app
